library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
capdata<-read.xlsx("Data.xlsx",sheetIndex = 3)
capdata=ts(capdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(capdata,xlab="Months",ylab="Capsule Sales")
plot(diff(capdata),ylab="Differenced Capsule sales")
plot(log10(capdata),ylab="log(Capsule sales)")
plot(diff(log10(capdata)),ylab="Differenced log Capsule sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(capdata))),main="Acf Capsule Sales")
pacf(ts(diff(log10(capdata))),main="Pacf Capsule Sales")
require(forecast)
ARIMAfitcap= auto.arima(log10(capdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitcap)
par(mfrow=c(1,1))
predcap=predict(ARIMAfitcap, n.ahead = 10)
predcap
plot(log10(capdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Capsule sales')
lines(10^(log10(predcap$pred)),col='blue')
lines(10^(log10(predcap$pred)+2*predcap$se),col='orange')
lines(10^(log10(predcap$pred)-2*predcap$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitcap$residuals),main='ACF Capsule Residual')
pacf(ts(ARIMAfitcap$residuals),main='PACF Capsule Residual')

