library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
creamdata<-read.xlsx("Data.xlsx",sheetIndex = 4)
creamdata=ts(creamdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(creamdata,xlab="Months",ylab="Cream Sales")
plot(diff(creamdata),ylab="Differenced Cream sales")
plot(log10(creamdata),ylab="log(Cream sales)")
plot(diff(log10(creamdata)),ylab="Differenced log Cream sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(creamdata))),main="Acf Cream Sales")
pacf(ts(diff(log10(creamdata))),main="Pacf Cream Sales")
require(forecast)
ARIMAfitcream= auto.arima(log10(creamdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitcream)
par(mfrow=c(1,1))
predcream=predict(ARIMAfitcream, n.ahead = 10)
predcream
plot(log10(creamdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Cream sales')
lines(10^(log10(predcream$pred)),col='blue')
lines(10^(log10(predcream$pred)+2*predcream$se),col='orange')
lines(10^(log10(predcream$pred)-2*predcream$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitcream$residuals),main='ACF Cream Residual')
pacf(ts(ARIMAfitcream$residuals),main='PACF Cream Residual')

