library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
dropsdata<-read.xlsx("Data.xlsx",sheetIndex = 5)
dropsdata=ts(dropsdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(dropsdata,xlab="Months",ylab="Drops Sales")
plot(diff(dropsdata),ylab="Differenced Drops sales")
plot(log10(dropsdata),ylab="log(Drops sales)")
plot(diff(log10(dropsdata)),ylab="Differenced log Drops sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(dropsdata))),main="Acf Drops Sales")
pacf(ts(diff(log10(dropsdata))),main="Pacf Drops Sales")
require(forecast)
ARIMAfitdrops= auto.arima(log10(dropsdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitdrops)
par(mfrow=c(1,1))
preddrops=predict(ARIMAfitdrops, n.ahead = 10)
preddrops
plot(log10(dropsdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Drops sales')
lines(10^(log10(preddrops$pred)),col='blue')
lines(10^(log10(preddrops$pred)+2*preddrops$se),col='orange')
lines(10^(log10(preddrops$pred)-2*preddrops$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitdrops$residuals),main='ACF Drops Residual')
pacf(ts(ARIMAfitdrops$residuals),main='PACF Drops Residual')

