library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
Geldata<-read.xlsx("Data.xlsx",sheetIndex = 6)
Geldata=ts(Geldata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(Geldata,xlab="Months",ylab="Gel Sales")
plot(diff(Geldata),ylab="Differenced Gel sales")
plot(log10(Geldata),ylab="log(Gel sales)")
plot(diff(log10(Geldata)),ylab="Differenced log Gel sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(Geldata))),main="Acf Gel Sales")
pacf(ts(diff(log10(Geldata))),main="Pacf Gel Sales")
require(forecast)
ARIMAfitgel= auto.arima(log10(Geldata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitgel)
par(mfrow=c(1,1))
predgel=predict(ARIMAfitgel, n.ahead = 10)
predgel
plot(log10(Geldata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Gel sales')
lines(10^(log10(predgel$pred)),col='blue')
lines(10^(log10(predgel$pred)+2*predgel$se),col='orange')
lines(10^(log10(predgel$pred)-2*predgel$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitgel$residuals),main='ACF Gel Residual')
pacf(ts(ARIMAfitgel$residuals),main='PACF Gel Residual')

