library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
Injdata<-read.xlsx("Data.xlsx",sheetIndex = 7)
Injdata=ts(Injdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(Injdata,xlab="Months",ylab="Injection Sales")
plot(diff(Injdata),ylab="Differenced Injection sales")
plot(log10(Injdata),ylab="log(Injection sales)")
plot(diff(log10(Injdata)),ylab="Differenced log Injection sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(Injdata))),main="Acf Injection Sales")
pacf(ts(diff(log10(Injdata))),main="Pacf Injection Sales")
require(forecast)
ARIMAfitInj= auto.arima(log10(Injdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitInj)
par(mfrow=c(1,1))
predinj=predict(ARIMAfitInj, n.ahead = 10)
predinj
plot(log10(Injdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Injection sales')
lines(10^(log10(predinj$pred)),col='blue')
lines(10^(log10(predinj$pred)+2*predinj$se),col='orange')
lines(10^(log10(predinj$pred)-2*predinj$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitInj$residuals),main='ACF Injection Residual')
pacf(ts(ARIMAfitInj$residuals),main='PACF Injection Residual')

