library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
Lotiondata<-read.xlsx("Data.xlsx",sheetIndex = 8)
Lotiondata=ts(Lotiondata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(Lotiondata,xlab="Months",ylab="Lotion Sales")
plot(diff(Lotiondata),ylab="Differenced Lotion sales")
plot(log10(Lotiondata),ylab="log(Lotion sales)")
plot(diff(log10(Lotiondata)),ylab="Differenced log Lotion sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(Lotiondata))),main="Acf Lotion Sales")
pacf(ts(diff(log10(Lotiondata))),main="Pacf Lotion Sales")
require(forecast)
ARIMAfitLotion= auto.arima(log10(Lotiondata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitLotion)
par(mfrow=c(1,1))
predlotion=predict(ARIMAfitLotion, n.ahead = 10)
predlotion
plot(log10(Lotiondata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Lotion sales')
lines(10^(log10(predlotion$pred)),col='blue')
lines(10^(log10(predlotion$pred)+2*predlotion$se),col='orange')
lines(10^(log10(predlotion$pred)-2*predlotion$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitLotion$residuals),main='ACF Lotion Residual')
pacf(ts(ARIMAfitLotion$residuals),main='PACF Lotion Residual')

