library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
Ointdata<-read.xlsx("Data.xlsx",sheetIndex = 9)
Ointdata=ts(Ointdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(Ointdata,xlab="Months",ylab="Ointment Sales")
plot(diff(Ointdata),ylab="Differenced Ointment sales")
plot(log10(Ointdata),ylab="log(Ointment sales)")
plot(diff(log10(Ointdata)),ylab="Differenced log Ointment sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(Ointdata))),main="Acf Ointment Sales")
pacf(ts(diff(log10(Ointdata))),main="Pacf Ointment Sales")
require(forecast)
ARIMAfitOint= auto.arima(log10(Ointdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitOint)
par(mfrow=c(1,1))
predoint=predict(ARIMAfitOint, n.ahead = 10)
predoint
plot(log10(Ointdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Ointment sales')
lines(10^(log10(predoint$pred)),col='blue')
lines(10^(log10(predoint$pred)+2*predoint$se),col='orange')
lines(10^(log10(predoint$pred)-2*predoint$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitOint$residuals),main='ACF Ointment Residual')
pacf(ts(ARIMAfitOint$residuals),main='PACF Ointment Residual')

