library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
Powderdata<-read.xlsx("Data.xlsx",sheetIndex = 10)
Powderdata=ts(Powderdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(Powderdata,xlab="Months",ylab="Powder Sales")
plot(diff(Powderdata),ylab="Differenced Powder sales")
plot(log10(Powderdata),ylab="log(Powder sales)")
plot(diff(log10(Powderdata)),ylab="Differenced log Powder sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(Powderdata))),main="Acf Powder Sales")
pacf(ts(diff(log10(Powderdata))),main="Pacf Powder Sales")
require(forecast)
ARIMAfitpowder= auto.arima(log10(Powderdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfitpowder)
par(mfrow=c(1,1))
predpowder=predict(ARIMAfitpowder, n.ahead = 10)
predpowder
plot(log10(Powderdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Powder sales')
lines(10^(log10(predpowder$pred)),col='blue')
lines(10^(log10(predpowder$pred)+2*predpowder$se),col='orange')
lines(10^(log10(predpowder$pred)-2*predpowder$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfitpowder$residuals),main='ACF Powder Residual')
pacf(ts(ARIMAfitpowder$residuals),main='PACF Powder Residual')

