library(forecast)
library(xlsx)
library(rJava)
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-9")
setwd("C:\\Users\\Ananth Kumar\\Desktop\\Months Data")
tabdata<-read.xlsx("Data.xlsx",sheetIndex = 2)
tabdata=ts(tabdata[,2],start=c(2017,1),end=c(2017,12),frequency = 12)
plot(tabdata,xlab="Months",ylab="Tablets Sales")
plot(diff(tabdata),ylab="Differenced Tablets sales")
plot(log10(tabdata),ylab="log(Tablets sales)")
plot(diff(log10(tabdata)),ylab="Differenced log Tablets sales")
par(mfrow=c(1,2)) 
acf(ts(diff(log10(tabdata))),main="Acf Tablets Sales")
pacf(ts(diff(log10(tabdata))),main="Pacf Tablets Sales")
require(forecast)
ARIMAfittab= auto.arima(log10(tabdata),approximation = FALSE,trace = FALSE)
summary(ARIMAfittab)
par(mfrow=c(1,1))
predtab=predict(ARIMAfittab, n.ahead = 10)
predtab
plot(log10(tabdata),type='l',xlim=c(2017,2019),ylim=c(4,8),xlab = 'Year',ylab = 'Tablets sales')
lines(10^(log10(predtab$pred)),col='blue')
lines(10^(log10(predtab$pred)+2*predtab$se),col='orange')
lines(10^(log10(predtab$pred)-2*predtab$se),col='orange')
par(mfrow=c(1,2))
acf(ts(ARIMAfittab$residuals),main='ACF Tablets Residual')
pacf(ts(ARIMAfittab$residuals),main='PACF Tablets Residual')
